config/routes.rb
Rails.application.routes.draw do
  resources :pedidos, except: [:create, :new] do
    resources :items, except: [:index, :new]
    member do
      put 'efetuar'
      put 'cancelar'
      put 'aceitar'
      put 'finalizar'
    end
  end
  devise_for :usuarios, controllers: {
      registrations: 'usuarios'
  }
  resources :produtos do
    resources :comentarios, except: [:index, :show]
  end
  resources :comentarios do
    resources :comentarios, except: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :usuario
  enum status: [:criando, :efetuado, :aprovado, :cancelado, :entregue]
  validates :status, presence: true

  def add_produto(produto)
    item_atual = items.find_by(produto_id: produto.id)

    if item_atual
      item_atual.increment(:quantidade)
    else
      item_atual = items.build(produto_id: produto.id)
    end
    item_atual
  end

  def preco_total
    items.to_a.sum { |item| item.preco_total }
  end

  def verificar_quantidade
    items.each do |item|
      if item.quantidade > item.produto.quantidade_estoque
        raise "Quantidade em estoque insuficiente"
      end
    end
  end

  def aceitar_pedido
    if status == 'efetuado'
      verificar_quantidade
      items.each do |item|
        qtd_estoque = item.produto.quantidade_estoque
        qtd_pedido = item.quantidade
        item.produto.update(quantidade_estoque: qtd_estoque - qtd_pedido)
      end
      self.update(status: :aprovado)
    end
  end

  def cancelar_pedido
    if self.status == 'aprovado'
      items.each do |item|
        qtd_estoque = item.produto.quantidade_estoque
        qtd_pedido = item.quantidade
        item.produto.update(quantidade_estoque: qtd_estoque + qtd_pedido)
      end
      self.update(status: :cancelado)
      true
    elsif self.status == 'efetuado'
      self.update(status: :cancelado)
    else
      false
    end
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  load_and_authorize_resource :pedido

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = @pedidos.where.not(status: :criando)
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/1/edit
  def edit
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    update_param(pedido_params)
  end

  def efetuar
    update_param(status: :efetuado)
  end

  def cancelar
    respond_to do |format|
      if @pedido.cancelar_pedido
        response_successfully(format, @pedido, 'Pedido was successfully updated.', :show, :ok)
      else
        response_unsuccessfully(format, :edit, @pedido, :unprocessable_entity)
      end
    end
  end

  def aceitar
    respond_to do |format|
      begin
        @pedido.aceitar_pedido
        response_successfully(format, @pedido, 'Pedido was successfully updated.', :show, :ok)
      rescue => exception
        format.json { head :forbidden }
        format.html { redirect_to @pedido, :alert => exception.message }
      end
    end
  end

  def finalizar
    update_param(status: :entregue)
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      response_successfully(format, pedidos_url, 'Pedido was successfully destroyed.', :show, :no_content)
    end
  end

  private

  def update_param(params)
    respond_to do |format|
      if @pedido.update(params)
        response_successfully(format, @pedido, 'Pedido was successfully updated.', :show, :ok)
      else
        response_unsuccessfully(format, :edit, @pedido, status: :unprocessable_entity)
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pedido_params
    params.require(:pedido).permit(:status, :usuario)
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
  def contagem_pedido_acima_de_1
    pedido_possui_items if pedido_possui_items > 0
  end

  def pedido_possui_items
    if @current
      total = @current.items.map(&:quantidade).sum
      total if total > 0
    end
  end

  def criando?
    @pedido.status == 'criando'
  end

  def cancelar?
    @pedido.status == 'efetuado' || @pedido.status == 'aprovado'
  end

  def aceitar?
    current_usuario.try(:admin) && @pedido.status == 'efetuado'
  end

  def finalizar?
    current_usuario.try(:admin) && @pedido.status == 'aprovado'
  end

  def refazer?
    @pedido.status == 'cancelado'
  end
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido, html: { class: "form-horizontal", role: "form" }) do |f| %>
<% if @pedido.errors.any? %>
<div class="alert alert-danger alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido
    from being saved:</h4>

  <ul>
    <% @pedido.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/pedidos/edit.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <%= link_to @pedido, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
  <% end %>
  <h1>Editing pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/index.html.erb
<div class="page-header">
  <h1>Pedidos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Cliente</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @pedidos) do |pedido| %>
      <td><%= pedido.usuario.nome %></td>
      <td><%= pedido.status %></td>
    <td><%= link_to 'Show', pedido, id: "ShowPedido-#{pedido.usuario.nome}" %></td>
    <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/pedidos/new.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <h1>New pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/show.html.erb
<div class="page-header">
  <% if criando? %>
    <%= link_to produtos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Continuar comprando
    <% end %>
  <% end %>
  <h1>Show pedido</h1>
</div>
<dl class="dl-horizontal">
  <dt>Status:</dt>
  <dd><%= @pedido.status %></dd>
  <dt>Cliente:</dt>
  <dd><%= @pedido.usuario.nome %></dd>
  <dt>Preço total</dt>
  <dd><%= @pedido.preco_total %></dd>
  <dt>Produtos:</dt>
  <dd></dd>
  <%= render @pedido.items %>
</dl>
<div class="btn-group" role="group">
  <% if criando? %>
    <%= button_to 'Finalizar pedido', efetuar_pedido_url(@pedido), id: 'finalizarPedidoUser',class: 'btn btn-success', method: :put %>
  <% end %>
  <% if cancelar? %>
    <%= button_to 'Cancelar pedido', cancelar_pedido_url(@pedido), id: "cancelarPedido", class: 'btn btn-danger', method: :put %>
  <% end %>
  <% if aceitar? %>
    <%= button_to 'Aceitar pedido', aceitar_pedido_url(@pedido), id: "aceitarPedido",class: 'btn btn-primary', method: :put %>
  <% end %>
  <% if finalizar? %>
    <%= button_to 'Finalizar pedido', finalizar_pedido_url(@pedido), id: "finalizarPedidoAdm",class: 'btn btn-info', method: :put %>
  <% end %>
  <% if refazer? %>
    <%= button_to 'Refazer pedido', efetuar_pedido_path(@pedido), id: "refazerPedido",class: 'btn btn-success', method: :put %>
  <% end %>
</div>