config/routes.rb
Rails.application.routes.draw do
  resources :pedidos, except: [:create, :new] do
    resources :items, except: [:index, :new]
    member do
      put 'efetuar'
      put 'cancelar'
      put 'aceitar'
      put 'finalizar'
    end
  end
  devise_for :usuarios, controllers: {
      registrations: 'usuarios'
  }
  resources :produtos do
    resources :comentarios, except: [:index, :show]
  end
  resources :comentarios do
    resources :comentarios, except: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :produto
  belongs_to :pedido

  def preco_total
    produto.preco * quantidade
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource :pedido
  load_and_authorize_resource :item, through: :pedido

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @produto = Produto.find(item_params[:produto_id])
    @item = @current.add_produto(@produto)

    respond_to do |format|
      if @item.save
        response_successfully(format, @current, 'Item was successfully created.', :show, :created)
      else
        response_unsuccessfully(format, :new, @current, :unprocessable_entity)
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        response_successfully(format, @pedido, 'Item was successfully updated.', :show, :ok)
      else
        response_unsuccessfully(format, :edit, @pedido, :unprocessable_entity)
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      response_successfully(format, @pedido, 'Item was successfully created.', :show, :no_content)
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:quantidade, :produto_id, :pedido_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@pedido, @item], html: {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item
        from being saved:</h4>

      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit id:'update', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<dl class="dl-horizontal">
  <dd>
    <dl class="dl-horizontal">
      <%= render item.produto %>
      <dt>Quantidade:</dt>
      <dd><%= item.quantidade %></dd>
      <dt>Preço</dt>
      <dd><%= item.preco_total %></dd>

      <% if can? :manage, Item %>
        <dd>
          <%= link_to 'Edit', edit_pedido_item_path(item.pedido, item), id: "edit-#{item.produto.codigo}" %>
          <%= link_to 'Destroy', pedido_item_path(item.pedido, item), method: :delete, data: {confirm: 'Are you sure?'}, id: "destroy-#{item.produto.codigo}" %>
          <div id="new-reply"></div>
        </dd>
      <% end %>
    </dl>
  </dd>
</dl>

app/views/items/edit.html.erb
<div class="page-header">
  <%= link_to @item.pedido, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <h1>Editing item</h1>
</div>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Item
  <% end %>
  <h1>Listing items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      
        <th>Produto</th>
      
        <th>Pedido</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @items) do |item| %>
    
      <td><%= item.produto %></td>
    
      <td><%= item.pedido %></td>
    
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Edit
  <% end %>
  <h1>Show item</h1>
</div>

<dl class="dl-horizontal">
    <dt>Produto:</dt>
    <dd><%= @item.produto %></dd>
    <dd><%= @item.quantidade %></dd>
</dl>