config/routes.rb
Rails.application.routes.draw do
  resources :pedidos, except: [:create, :new] do
    resources :items, except: [:index, :new]
    member do
      put 'efetuar'
      put 'cancelar'
      put 'aceitar'
      put 'finalizar'
    end
  end
  devise_for :usuarios, controllers: {
      registrations: 'usuarios'
  }
  resources :produtos do
    resources :comentarios, except: [:index, :show]
  end
  resources :comentarios do
    resources :comentarios, except: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/produto.rb
class Produto < ApplicationRecord
  before_destroy :nao_e_referenciado
  has_many :comentarios, as: :comentavel, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :codigo, presence: true
  validates :nome, presence: true
  validates :marca, presence: true
  validates :quantidade_estoque, presence: true
  validates :preco, presence: true

  private

  def nao_e_referenciado
    unless items.empty?
      errors.add(:base, "Existem itens que referenciam esse produto")
      throw :abort
    end
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  load_and_authorize_resource

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        response_successfully(format, @produto, 'Produto was successfully created.', :show, :created)
      else
        response_unsuccessfully(format, :new, @produto, :unprocessable_entity)
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        response_successfully(format, @produto, 'Produto was successfully updated.', :show, :ok)
      else
        response_unsuccessfully(format, :edit, @produto, :unprocessable_entity)
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    respond_to do |format|
      @produto.destroy
      response_successfully(format, produtos_url, 'Produto was successfully destroyed.', :show, :no_content)
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def produto_params
    params.require(:produto).permit(:codigo, :nome, :marca, :quantidade_estoque, :preco)
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, html: {class: "form-horizontal", role: "form"}) do |f| %>

  <%= render "devise/shared/error_messages", resource: @produto %>

  <div class="form-group">
    <%= f.label :codigo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :codigo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :marca, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :marca, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quantidade_estoque, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade_estoque, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :preco, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :preco, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit id: 'cadastrar', class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/produtos/_produto.html.erb
<dt>Código:</dt>
<dd><%= produto.codigo %></dd>
<dt>Nome:</dt>
<dd><%= produto.nome %></dd>
<dt>Marca:</dt>
<dd><%= produto.marca %></dd>
<dt>Quantidade estoque:</dt>
<dd><%= produto.quantidade_estoque %></dd>
<dt>Preço unitário:</dt>
<dd><%= produto.preco %></dd>

app/views/produtos/edit.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <% if current_usuario.try(:admin?) %>
    <%= link_to new_produto_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Produto
    <% end %>
  <% end %>
  <h1>Listing produtos</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Marca</th>
      <th>Quantidade estoque</th>
      <th>Preço</th>
      <th></th>
      <% if can? :read && :destroy, Produto %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @produtos) do |produto| %>
      <td><%= produto.codigo %></td>
      <td><%= produto.nome %></td>
      <td><%= produto.marca %></td>
      <td><%= produto.quantidade_estoque %></td>
      <td><%= produto.preco %></td>
      <td><%= link_to 'Show', produto, id: "s-#{produto.codigo}" %></td>
      <% if can? :read && :destroy, Produto %>
        <td><%= link_to 'Edit', edit_produto_path(produto), id: "e-#{produto.codigo}" %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: {confirm: 'Are you sure?'}, id: "d-#{produto.codigo}" %></td>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/produtos/new.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/show.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <% if can? :update, @produto %>
    <%= link_to edit_produto_path(@produto), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
  <% end %>
  <% if can? :create, Comentario %>
    <%= link_to "Create comentario", new_produto_comentario_path(@produto), id: 'criarComentario', class: 'btn btn-primary'%>
  <% end %>
  <% if @current %>
    <%= button_to 'Adicionar ao carrinho', pedido_items_path(pedido_id: @current, item: {produto_id: @produto}),
                  id: 'adicionarAoCarrinho', method: :post, class: 'btn btn-success' %>
  <% end %>
  <h1>Produto</h1>
</div>
<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @produto.codigo %></dd>
  <dt>Nome:</dt>
  <dd><%= @produto.nome %></dd>
  <dt>Marca:</dt>
  <dd><%= @produto.marca %></dd>
  <dt>Quantidade estoque:</dt>
  <dd><%= @produto.quantidade_estoque %></dd>
  <dt>Preço:</dt>
  <dd><%= @produto.preco %></dd>
</dl>
<div class="page-header">
  <h1>Show comentarios</h1>
</div>

<%= render @produto.comentarios %>