config/routes.rb
Rails.application.routes.draw do
  resources :pedidos, except: [:create, :new] do
    resources :items, except: [:index, :new]
    member do
      put 'efetuar'
      put 'cancelar'
      put 'aceitar'
      put 'finalizar'
    end
  end
  devise_for :usuarios, controllers: {
      registrations: 'usuarios'
  }
  resources :produtos do
    resources :comentarios, except: [:index, :show]
  end
  resources :comentarios do
    resources :comentarios, except: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Charme modas web", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Produto', produtos_path %></li>
        <% if can? :read, Pedido %>
          <li><%= link_to 'Pedido', pedidos_path %></li>
        <% end %>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if pedido_possui_items %>
          <li>
            <%= link_to pedido_path(@current) do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
              Carrinho <%= contagem_pedido_acima_de_1 %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless usuario_signed_in? %>
          <li><%= link_to 'Sign up', new_usuario_registration_path %></li>
          <li><%= link_to 'Log in', new_usuario_session_path %></li>
        <% else %>
          <li><%= link_to 'Log out', destroy_usuario_session_path, method: :delete %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= flash_message.html_safe %>
  <%= yield %>
</div>
</body>
</html>